sonar.projectKey=playwright-qa-poc
sonar.organization=henriqsouza
sonar.projectName=Playwright QA POC
sonar.sources=tests
sonar.exclusions=**/node_modules/**,**/test-results/**,**/playwright-report/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
